Add missing functions/classes to __all__ (#757)
* Add CollectorRegistry&REGISTRY to __init__.py
* Set implicit_reexport to False
* Add functions/classes to __all__
* Add __all__ to exposition.py

prometheus_client/__init__.py:7: error: Module "prometheus_client.exposition" does not explicitly export attribute "make_asgi_app"; implicit reexport disabled

Signed-off-by: Yury Pliner <yury.pliner@gmail.com>